import type { BoardSpaceProperty } from "env";

export const tmpData: BoardSpaceProperty[] = [
    { type: 'go', class: { corner: true, go: true }, name: 'Go', instruction: 'Collect $200.00 salary as you pass'},
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Connecticut Avenue', price: 'Price $120', },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Vermont Avenue', price: 'Price $100', },
    { type: 'chance', class: { chance: true }, name: 'Chance' },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Oriental Avenue', price: 'Price $100', },
    { type: 'special', class: { 'fa-subway': true }, name: 'Reading Railroad', price: 'Price $200' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'special', class: { 'fa-cube': true }, name: 'Community Chest', instruction: 'Follow instructions on top card' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Mediter-\nranean\nAvenue', price: 'Price $50', },

    { type: 'jail', class: { corner: true, jail: true }, name: '전세사기', instruction: '전세사기를 당해\n3턴동안 휴식'},
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Connecticut Avenue', price: 'Price $120', },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Vermont Avenue', price: 'Price $100', },
    { type: 'chance', class: { chance: true }, name: 'Chance' },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Oriental Avenue', price: 'Price $100', },
    { type: 'special', class: { 'fa-subway': true }, name: 'Reading Railroad', price: 'Price $200' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'special', class: { 'fa-cube': true }, name: 'Community Chest', instruction: 'Follow instructions on top card' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Mediter-\nranean\nAvenue', price: 'Price $50', },

    { type: 'parking', class: { corner: true, 'free-parking': true }, name: '매물\n검색중'},
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Connecticut Avenue', price: 'Price $120', },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Vermont Avenue', price: 'Price $100', },
    { type: 'chance', class: { chance: true }, name: 'Chance' },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Oriental Avenue', price: 'Price $100', },
    { type: 'special', class: { 'fa-subway': true }, name: 'Reading Railroad', price: 'Price $200' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'special', class: { 'fa-cube': true }, name: 'Community Chest', instruction: 'Follow instructions on top card' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Mediter-\nranean\nAvenue', price: 'Price $50', },

    { type: 'gotojail', class: { corner: true, 'go-to-jail': true }, name: '전세사기를\n당했습니다.', instruction: '전세사기 칸으로 이동'},
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Connecticut Avenue', price: 'Price $120', },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Vermont Avenue', price: 'Price $100', },
    { type: 'chance', class: { chance: true }, name: 'Chance' },
    { type: 'property', class: { property: true, 'light-blue': true }, name: 'Oriental Avenue', price: 'Price $100', },
    { type: 'special', class: { 'fa-subway': true }, name: 'Reading Railroad', price: 'Price $200' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Baltic Avenue', price: 'Price $50', },
    { type: 'special', class: { 'fa-cube': true }, name: 'Community Chest', instruction: 'Follow instructions on top card' },
    { type: 'property', class: { property: true, 'dark-purple': true }, name: 'Mediter-\nranean\nAvenue', price: 'Price $50', },
];